"""add vehicle driver_rut and other changes

Revision ID: b1324d93ee1d
Revises: 
Create Date: 2025-10-22 00:21:03.035331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1324d93ee1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        # Provide an explicit name for the foreign key constraint to satisfy Alembic/SQLite
        batch_op.create_foreign_key('fk_mechanic_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_rut', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('driver_rut')

    with op.batch_alter_table('mechanic', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mechanic_user_id', type_='foreignkey')

    # ### end Alembic commands ###
