"""add region and comuna to access_entry

Revision ID: d5a4a3a3de01
Revises: d8765f43bc2a
Create Date: 2025-10-26 20:26:53.017972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a4a3a3de01'
down_revision = 'd8765f43bc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('comuna', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_entry', schema=None) as batch_op:
        batch_op.drop_column('comuna')
        batch_op.drop_column('region')

    # ### end Alembic commands ###
